runtime: python312

default_expiration: "180d 0h"

handlers:
- url: /images/favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /css
  static_dir: static/css
  http_headers:
    Vary: Accept-Encoding
- url: /js
  static_dir: static/js
  http_headers:
    Vary: Accept-Encoding
- url: /images
  static_dir: static/images
  http_headers:
    Vary: Accept-Encoding
- url: /materialize
  static_dir: static/materialize
  http_headers:
    Vary: Accept-Encoding
- url: /privacy_policy.txt
  static_files: static/privacy_policy.txt
  upload: static/privacy_policy.txt
- url: /.*
  script: main.app
