application: wag-on
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images/favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /images
  static_dir: static/images
- url: /materialize
  static_dir: static/materialize
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
