application: wag-on
version: 2
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "800d 0h"

handlers:
- url: /images/favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /css
  static_dir: static/css
  http_headers:
    Vary: Accept-Encoding
- url: /js
  static_dir: static/js
  http_headers:
    Vary: Accept-Encoding
- url: /images
  static_dir: static/images
  http_headers:
    Vary: Accept-Encoding
- url: /materialize
  static_dir: static/materialize
  http_headers:
    Vary: Accept-Encoding
- url: /css/main.css
  static_dir: static/css/main.css
  expiration: "10d 0h"
  http_headers:
    Vary: Accept-Encoding
- url: /js/main.js
  static_dir: static/js/main.js
  expiration: "10d 0h"
  http_headers:
    Vary: Accept-Encoding
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
